### PR TITLE
Stop running workflow when editing PR description

### PR DESCRIPTION
**Pull request by martinber**

### CODE REVIEW

**Comment by gekorob** [comment]
Just a question: Have you evaluated if this will stop the workflow from running also in case of a change in the base branch of the PR? I know that it's a corner case but it's something that is not so clear in the GITHub docs and I don't know if this behavior has been changed or not.

```
  type      |                          description
-------------------------------------------------------------------------------
edited     |       title, body, or the base branch of the PR is modified
```

**Comment by martinber** [comment]
I didnt test. I assume the important one is synchronized from [what I read in this website](https://docs.github.com/developers/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=edited#pull_request):

image
image
 
I think the table you sent in the previous comment is outdated, where did you get it?

**Comment by gekorob** [comment]
I got it crawling on the issues on Github, but maybe you're right and it's outdated, but it was what years ago made us adding edited to the actions.

**Review by gekorob — APPROVED** [review]
LGTM

**Pull request merged**
